---
services:
  prometheus:
    image: docker.io/prom/prometheus:v2.55.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus

  grafana:
    image: docker.io/grafana/grafana-oss:11.4.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local